[2024-05-10T08:20:29.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T08:20:29.799+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_process_dag.process_file manual__2024-05-10T08:20:28.219903+00:00 [queued]>
[2024-05-10T08:20:29.806+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_process_dag.process_file manual__2024-05-10T08:20:28.219903+00:00 [queued]>
[2024-05-10T08:20:29.806+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-10T08:20:29.819+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_file> on 2024-05-10 08:20:28.219903+00:00
[2024-05-10T08:20:29.824+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T08:20:29.825+0000] {standard_task_runner.py:63} INFO - Started process 102 to run task
[2024-05-10T08:20:29.825+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'file_process_dag', 'process_file', 'manual__2024-05-10T08:20:28.219903+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/from_folder_to_other.py', '--cfg-path', '/tmp/tmpgfay4bbz']
[2024-05-10T08:20:29.826+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask process_file
[2024-05-10T08:20:29.903+0000] {task_command.py:426} INFO - Running <TaskInstance: file_process_dag.process_file manual__2024-05-10T08:20:28.219903+00:00 [running]> on host 24b77fb676b2
[2024-05-10T08:20:30.029+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_process_dag' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T08:20:28.219903+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T08:20:28.219903+00:00'
[2024-05-10T08:20:30.030+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T08:20:30.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T08:20:30.061+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_folder_to_other.py", line 15, in process_file
    if filename.endwith('.txt'):
       ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'endwith'. Did you mean: 'endswith'?
[2024-05-10T08:20:30.068+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=file_process_dag, task_id=process_file, execution_date=20240510T082028, start_date=20240510T082029, end_date=20240510T082030
[2024-05-10T08:20:30.108+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task process_file ('str' object has no attribute 'endwith'; 102)
[2024-05-10T08:20:30.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T08:20:30.132+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T08:20:30.142+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
