[2024-05-10T10:46:22.725+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:22.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:46:22.727+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:46:22.727+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:22.743+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:46:22.735+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:46:22.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:22.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.062 seconds
[2024-05-10T10:46:52.912+0000] {processor.py:161} INFO - Started process (PID=2118) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:52.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:46:52.915+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:46:52.914+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:52.929+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:46:52.921+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:46:52.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:46:52.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.054 seconds
[2024-05-10T10:47:23.146+0000] {processor.py:161} INFO - Started process (PID=2125) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:23.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:47:23.150+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:47:23.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:23.167+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:47:23.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:47:23.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:23.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.071 seconds
[2024-05-10T10:47:53.346+0000] {processor.py:161} INFO - Started process (PID=2132) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:53.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:47:53.350+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:47:53.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:53.368+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:47:53.359+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:47:53.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:47:53.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.071 seconds
[2024-05-10T10:48:23.574+0000] {processor.py:161} INFO - Started process (PID=2139) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:23.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:48:23.577+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:48:23.576+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:23.592+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:48:23.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:48:23.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:23.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.061 seconds
[2024-05-10T10:48:53.777+0000] {processor.py:161} INFO - Started process (PID=2146) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:53.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:48:53.780+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:48:53.780+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:53.800+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:48:53.788+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:48:53.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:48:53.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.072 seconds
[2024-05-10T10:49:23.981+0000] {processor.py:161} INFO - Started process (PID=2153) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:23.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:49:23.985+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:23.984+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:24.002+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:23.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:49:24.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:24.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.068 seconds
[2024-05-10T10:49:54.194+0000] {processor.py:161} INFO - Started process (PID=2160) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:54.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:49:54.200+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:54.199+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:54.216+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:54.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 5, in <module>
    from scripts.text_processing.basic_processing import (
  File "/opt/airflow/dags/scripts/text_processing/basic_processing.py", line 54
    if filename.endswith(".txt")
                                ^
SyntaxError: expected ':'
[2024-05-10T10:49:54.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:49:54.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.123 seconds
[2024-05-10T10:50:24.366+0000] {processor.py:161} INFO - Started process (PID=2167) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:24.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:50:24.368+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:24.368+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:24.372+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:24.371+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 5, in <module>
    from scripts.text_processing.basic_processing import (
  File "/opt/airflow/dags/scripts/text_processing/basic_processing.py", line 54
    if filename.endswith(".txt")
                                ^
SyntaxError: expected ':'
[2024-05-10T10:50:24.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:24.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.035 seconds
[2024-05-10T10:50:54.546+0000] {processor.py:161} INFO - Started process (PID=2174) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:54.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:50:54.548+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:54.547+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:54.551+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:54.551+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 5, in <module>
    from scripts.text_processing.basic_processing import (
  File "/opt/airflow/dags/scripts/text_processing/basic_processing.py", line 54
    if filename.endswith(".txt")
                                ^
SyntaxError: expected ':'
[2024-05-10T10:50:54.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:50:54.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.034 seconds
[2024-05-10T10:51:24.819+0000] {processor.py:161} INFO - Started process (PID=2181) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:24.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:51:24.823+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:24.822+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:24.867+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:24.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/text_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/text_processing.py", line 43, in <module>
    python_callable=remove_html_errors,
                    ^^^^^^^^^^^^^^^^^^
NameError: name 'remove_html_errors' is not defined
[2024-05-10T10:51:24.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:24.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.107 seconds
[2024-05-10T10:51:52.961+0000] {processor.py:161} INFO - Started process (PID=2188) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:52.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:51:52.963+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:52.963+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:52.972+0000] {processor.py:840} INFO - DAG(s) 'file_process_dag' retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:51:53.065+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:53.065+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T10:51:53.074+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:53.074+0000] {dag.py:3954} INFO - Setting next_dagrun for file_process_dag to None, run_after=None
[2024-05-10T10:51:53.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.155 seconds
[2024-05-10T10:52:23.242+0000] {processor.py:161} INFO - Started process (PID=2195) to work on /opt/airflow/dags/text_processing.py
[2024-05-10T10:52:23.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/text_processing.py for tasks to queue
[2024-05-10T10:52:23.252+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:23.252+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/text_processing.py
[2024-05-10T10:52:23.263+0000] {processor.py:840} INFO - DAG(s) 'file_process_dag' retrieved from /opt/airflow/dags/text_processing.py
[2024-05-10T10:52:23.284+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:23.284+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T10:52:23.296+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:23.296+0000] {dag.py:3954} INFO - Setting next_dagrun for file_process_dag to None, run_after=None
[2024-05-10T10:52:23.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/text_processing.py took 0.084 seconds
